import os
from string import Template
from dotenv import load_dotenv

load_dotenv()

EMAIL_ADDR = os.getenv("EMAIL_ADDR")
EMAIL_KEY = os.getenv("EMAIL_KEY")
SENDER_NAME = os.getenv("SENDER_NAME")
SENDER = f"{SENDER_NAME} <{EMAIL_ADDR}>"

SMTP_SERVER = os.getenv("SMTP_SERVER")
SMTP_PORT = os.getenv("SMTP_PORT")

CSV_FN = os.getenv("CSV_FN")
CSV_NAME_FIELD = os.getenv("CSV_NAME_FIELD")
CSV_ID_FIELD = os.getenv("CSV_ID_FIELD")
EXIST_FN = os.getenv("EXIST_FN")

PASS_DIGIT = 16
PASS_DICT = '0123456789ABCDEF'

CLASS_NAME = os.getenv("CLASS_NAME")
WEBSITE = os.getenv("WEBSITE")
SUBJECT_TEMPLATE = Template("""[$CLASS_NAME] OJ 帳號密碼""")
BODY_TEMPLATE = Template("""
$NAME 同學好,

此信件由腳本產生，若您已經擁有 NCCUOJ 帳號，請忽略以下信件。

歡迎加入 $CLASS_NAME。以下是您的 OnlineJudge 帳號密碼：

網址：$WEBSITE
帳號：$ACCOUNT
密碼：$PASSWORD


請勿與任何人分享此信件。另外，為避免您忘記密碼，請在第一次登入後盡速修改密碼。

祝同學學業順利。
$CLASS_NAME 助教群

---

Dear $NAME,

This email was generated by a script. If you already have a NCCUOJ account, please disregard this email.

Welcome to $CLASS_NAME. Below are your OnlineJudge account credentials:

Website: $WEBSITE
Username: $ACCOUNT
Password: $PASSWORD

Please DO NOT share this email with anyone. Additionally, to prevent forgetting your password, please change it as soon as possible after your first login.

Wishing you success in your studies.

Best regards,
$CLASS_NAME Teaching Assistants
""")
RECIPIENT_TEMPLATE = Template("""$ACCOUNT@g.nccu.edu.tw""")

OUTPUT_CSV_FN = os.getenv("OUTPUT_CSV_FN")
